--- pyproject.toml.orig	2024-08-25 07:41:54 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["scikit-build-core>=0.10", "pybind11>=2.13.3"]
+requires = ["scikit-build-core", "pybind11>=2.13.3"]
 build-backend = "scikit_build_core.build"
 
 [project]
@@ -91,8 +91,6 @@ Homepage = "https://github.com/scikit-hep/boost-histog
 
 
 [tool.scikit-build]
-minimum-version = "build-system.requires"
-cmake.version = "CMakeLists.txt"
 metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
 sdist.exclude = [
   "extern/**/*.py",
