Obtained from:	https://github.com/python-openapi/openapi-core/commit/4054861cc9ad7c0baef2746552d9a598f65b41aa

--- pyproject.toml.orig	2023-09-14 11:17:27 UTC
+++ pyproject.toml
@@ -68,7 +68,7 @@ isodate = "*"
 more-itertools = "*"
 parse = "*"
 openapi-schema-validator = "^0.6.0"
-openapi-spec-validator = "^0.6.0"
+openapi-spec-validator = ">=0.6.0,<0.8.0"
 requests = {version = "*", optional = true}
 werkzeug = "*"
 jsonschema-spec = "^0.2.3"
