PORTNAME=	piewm
PORTVERSION=	1.04
PORTREVISION=	4
CATEGORIES=	x11-wm
MASTER_SITES=	https://ftp.openbsd.org/pub/OpenBSD/distfiles/

MAINTAINER=	david@catwhisker.org
COMMENT=	tvtwm with pie (circular) menus
WWW=		https://web.archive.org/web/20160409071502if_/http://www.crynwr.com/piewm/index.html~

USES=		imake xorg
DISABLE_SIZE=	yes
USE_XORG=	xbitmaps xpm xmu

CFLAGS+=	-Wno-return-type

.include <bsd.port.mk>
