--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -47,7 +47,7 @@ all = [
 all = [
     'phonenumbers>=8,<9',
     'pycountry>=23,<24',
-    'python-ulid>=1,<2',
+    'python-ulid>=1',
 ]
 
 [project.urls]
