Obtained from:	https://github.com/pypa/pip-audit/commit/20e7beece90b117687978205073435f8a54866cc

--- pyproject.toml.orig	2023-07-24 18:47:23 UTC
+++ pyproject.toml
@@ -30,7 +30,7 @@ dependencies = [
     "CacheControl[filecache] >= 0.13.0",
     # NOTE(ww): Release 2.5.0 is broken, subsequent 2.5.x releases fix it.
     # See: https://github.com/CycloneDX/cyclonedx-python-lib/issues/245
-    "cyclonedx-python-lib ~= 4.0",
+    "cyclonedx-python-lib >= 4,< 6",
     "html5lib>=1.1",
     "packaging>=23.0.0",               # https://github.com/pypa/pip-audit/issues/464
     "pip-api>=0.0.28",
