--- pyproject.toml.orig	2024-01-03 18:51:44 UTC
+++ pyproject.toml
@@ -17,10 +17,7 @@ dependencies = [
 # pip dependencies of the project
 dependencies = [
     # Ensure numpy release supports Python version.
-    "numpy>1.20",
-    "numpy>=1.21.2; python_version>='3.10'",
-    "numpy>=1.23.3; python_version>='3.11'",
-    "numpy>=1.26.0; python_version>='3.12'",
+    "numpy>=1.23.3",
 ]
 
 [project.urls]
@@ -49,10 +46,8 @@ requires = [
 [build-system]
 requires = [
     # Build with oldest supported numpy for each Python version.
-    "numpy~=1.21.2; python_version<'3.11'",
-    "numpy~=1.23.3; python_version>='3.11' and python_version<'3.12'",
-    "numpy~=1.26.0; python_version>='3.12'",
-    "setuptools~=68.1.0",
+    "numpy>=1.23.3",
+    "setuptools",
 ]
 build-backend = "setuptools.build_meta"
 
