PKGNAMESUFFIX=	-tools
MASTERDIR=	${.CURDIR}/../heartwood


PLIST_FILES+=	bin/rad-agent
PLIST_FILES+=	bin/rad-cli-demo
PLIST_FILES+=	bin/rad-init
PLIST_FILES+=	bin/rad-merge
PLIST_FILES+=	bin/rad-push
PLIST_FILES+=	bin/rad-self
PLIST_FILES+=	bin/rad-set-canonical-refs

CARGO_INSTALL_PATH=	radicle-tools

.include "${MASTERDIR}/Makefile.inc"
