    COMMENT = HardenedBSD projects

SUBDIR += hardenedbsd-meta
SUBDIR += hbsdmon
SUBDIR += kernel-nodebug
SUBDIR += liblattutil
SUBDIR += secadm
SUBDIR += secadm-kmod
SUBDIR += testmprotect
SUBDIR += testpie

.include <bsd.port.subdir.mk>
