PORTNAME=	heartwood
DISTVERSION=	1.0-rc11
CATEGORIES=	net-p2p devel

MAINTAINER=	shawn.webb@hardenedbsd.org
COMMENT=	Metaport for Radicle, a sovereign code forge built on Git
WWW=		https://radicle.xyz/

RUN_DEPENDS=	heartwood-cli>=0:net-p2p/heartwood-cli
#RUN_DEPENDS+=	heartwood-httpd>=0:net-p2p/heartwood-httpd
RUN_DEPENDS+=	heartwood-node>=0:net-p2p/heartwood-node
RUN_DEPENDS+=	heartwood-remote-helper>=0:net-p2p/heartwood-remote-helper
RUN_DEPENDS+=	heartwood-tools>=0:net-p2p/heartwood-tools

USES=		metaport

.include <bsd.port.mk>
