--- pyproject.toml.orig	2023-09-26 19:15:41 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools_scm[toml]>=4,<8", "cython<3", "cmake>=3.24.2; python_version>='3.6'"]
+requires = ["setuptools_scm[toml]>=4,<8", "cython<3"]
 build-backend = "setuptools.build_meta"
 
 [project]
